#!/bin/bash
set -e
gcc ran.c -o ranc
for f in `ls test/*.c`; do
  echo "testing $f"
  ./ranc < $f > a.s
  gcc -m32 a.s
  ./a.out > actual.out
  expect=${f%.c}.out
  diff actual.out $expect
  if [ $? -ne 0 ]; then
    echo "failed"
    exit -1
  fi
  echo "passed"
  rm a.s a.out actual.out
done
