#!/bin/bash
set -e

function test_with() {
  ranc=$1
  for f in `ls test/*.c`; do
    echo "testing $f"
    $ranc < $f > a.s
    gcc -m32 a.s
    ./a.out > actual.output
    expect=${f%.c}.output
    diff actual.output $expect
    echo "passed"
    rm a.s a.out actual.output
  done
}

test_with ./ranc
echo
echo "****** test bootstraping ******"
echo
./bootstrap
test_with ./ranc
